---
- name: create {{ _docker_compose_project_label }} directory
  file:
    dest: "{{ _docker_compose_project_dir }}"
    state: directory
    owner: "{{ _docker_compose_project_owner }}"
    group: "{{ _docker_compose_project_group }}"
    mode: "{{ _docker_compose_project_dir_mode }}"

- block:
    - name: generate {{ _docker_compose_project_label }} compose file
      ansible.builtin.template:
        src: docker-compose.yaml.j2
        dest: "{{ _docker_compose_project_dir }}/{{ _docker_compose_compose_file }}"
        owner: "{{ _docker_compose_project_owner }}"
        group: "{{ _docker_compose_project_group }}"
        mode: "{{ _docker_compose_project_mode }}"

    - name: remove previous {{ _docker_compose_project_label }} compose files
      ansible.builtin.file:
        dest: "{{ _docker_compose_project_dir }}/{{ compose_file }}"
        state: absent
      loop: "{{ docker_compose_remove_compose_files }}"
      loop_control:
        loop_var: compose_file
      when:
        - docker_compose_remove_other_compose_files
        - compose_file != _docker_compose_compose_file

    - name: pull {{ _docker_compose_project_label }} docker images
      community.docker.docker_image:
        name: "{{ container.image.name if container.image is mapping else container.image }}"
        tag: "{{ container.image.tag | default('latest') if container.image is mapping else 'latest' }}"
        source: pull
      loop: "{{ _docker_compose_containers }}"
      loop_control:
        loop_var: container
        label: "{{ { 'service': container.service_name, 'image': container.image } }}"
      when: _docker_compose_pull_images

    - block:
        - name: determine {{ _docker_compose_project_label }} volume bind mounts
          ansible.builtin.set_fact:
            _docker_compose_bind_mounts: "{{ _docker_compose_bind_mounts + [ volume | combine({'source': volume.source if volume.source.startswith('/') else _docker_compose_project_dir ~ '/' ~ volume.source })] }}"
          loop: "{{ _docker_compose_containers | selectattr('volumes', 'defined') | map(attribute='volumes') | flatten | selectattr('source', 'defined') }}"
          loop_control:
            loop_var: volume
            label: "{{ volume.source if volume.source.startswith('/') else _docker_compose_project_dir ~ '/' ~ volume.source }}"
          vars:
            _docker_compose_bind_mounts: []

        - name: bind {{ _docker_compose_project_label }} directories
          ansible.builtin.file:
            dest: "{{ volume.source if volume.source.startswith('/') else _docker_compose_project_dir ~ '/' ~ volume.source }}"
            state: directory
            owner: "{{ volume.owner | default(_docker_compose_project_bind_file_owner) }}"
            group: "{{ volume.group | default(_docker_compose_project_bind_file_group) }}"
            mode: "{{ volume.mode | default(_docker_compose_project_bind_file_mode) }}"
          loop: "{{ _docker_compose_bind_mounts | rejectattr('template', 'defined') | rejectattr('file', 'defined') }}"
          loop_control:
            loop_var: volume
            label: "{{ volume.source }}"
          when:
            - (volume.type | default('bind')) == 'bind'
            - volume.create | default(true)

        - name: bind {{ _docker_compose_project_label }} files from templates
          ansible.builtin.template:
            src: "{{ volume.template }}"
            dest: "{{ volume.source if volume.source.startswith('/') else _docker_compose_project_dir ~ '/' ~ volume.source }}"
            owner: "{{ volume.owner | default(_docker_compose_project_bind_file_owner) }}"
            group: "{{ volume.group | default(_docker_compose_project_bind_file_group) }}"
            mode: "{{ volume.mode | default(_docker_compose_project_bind_file_mode) }}"
          loop: "{{ _docker_compose_bind_mounts | selectattr('template', 'defined') | rejectattr('file', 'defined') }}"
          loop_control:
            loop_var: volume
            label: "{{ volume.source }}"
          when:
            - (volume.type | default('bind')) == 'bind'
            - volume.create | default(true)

        - name: bind {{ _docker_compose_project_label }} files from sources
          ansible.builtin.copy:
            src: "{{ volume.file }}"
            dest: "{{ volume.source if volume.source.startswith('/') else _docker_compose_project_dir ~ '/' ~ volume.source }}"
            owner: "{{ volume.owner | default(_docker_compose_project_bind_file_owner) }}"
            group: "{{ volume.group | default(_docker_compose_project_bind_file_group) }}"
            mode: "{{ volume.mode | default(_docker_compose_project_bind_file_mode) }}"
          loop: "{{ _docker_compose_bind_mounts | selectattr('file', 'defined') | rejectattr('template', 'defined') }}"
          loop_control:
            loop_var: volume
            label: "{{ volume.source }}"
          when:
            - (volume.type | default('bind')) == 'bind'
            - volume.create | default(true)
      when: _docker_compose_create_mounts

    - name: create {{ _docker_compose_project_label }} env files
      ansible.builtin.include_tasks: create-env-file.yaml
      loop: "{{ _docker_compose_containers | selectattr('env_file', 'defined') }}"
      loop_control:
        label: "{{ container.service_name }}"
        loop_var: container

    - name: start {{ _docker_compose_project_label }} 
      community.docker.docker_compose_v2:
        state: present
        project_src: "{{ _docker_compose_project_dir }}"
        files:
          - "{{ _docker_compose_compose_file }}"
      when: _docker_compose_autostart
  when: _docker_compose_containers | length > 0
