---
- name: create {{ _project_label }} directory
  file:
    dest: "{{ _project_dir }}"
    state: directory
    owner: "{{ _project_owner }}"
    group: "{{ _project_group }}"
    mode: "{{ _project_dir_mode }}"

- block:
    - name: generate {{ _project_label }} compose file
      ansible.builtin.template:
        src: compose.yaml.j2
        dest: "{{ _project_dir }}/{{ _compose_file }}"
        owner: "{{ _project_owner }}"
        group: "{{ _project_group }}"
        mode: "{{ _compose_file_mode }}"

    - name: remove previous {{ _project_label }} compose files
      ansible.builtin.file:
        dest: "{{ _project_dir }}/{{ _remove_compose_file }}"
        state: absent
      loop: "{{ compose_remove_compose_files }}"
      loop_control:
        loop_var: _remove_compose_file
      when:
        - compose_remove_other_compose_files
        - _remove_compose_file != _compose_file

    - name: create {{ _project_label }} compose env file
      ansible.builtin.include_tasks: create-env-file.yaml
      when:
        - project.env_file is defined
      vars:
        service:
          env_file: >-
            [
              {{
                project.env_file | combine({
                  'path': _project_dir ~ '/.env'
                })
              }}
            ]

    - name: remove {{ _project_label }} compose env file
      ansible.builtin.file:
        dest: "{{ _project_dir }}/.env"
        state: absent
      when:
        - project.env_file is not defined

    - name: pull {{ _project_label }} docker images
      community.docker.docker_image:
        name: "{{ service.image.name if service.image is mapping else service.image }}"
        tag: "{{ service.image.tag | default('latest') if service.image is mapping else 'latest' }}"
        source: pull
      loop: "{{ _services | selectattr('image', 'defined') | rejectattr('build', 'defined') }}"
      loop_control:
        loop_var: service
        label: "{{ { 'service': service.name, 'image': service.image } }}"
      when: _pull_images

    - name: create {{ _project_label }} build context
      ansible.builtin.include_tasks: create-build-context.yaml   
      loop: "{{ _services | selectattr('build', 'defined') }}"
      loop_control:
        label: "{{ service.name }}"
        loop_var: service
      when:
        - service.build.context is defined or service.build.src is defined or service.build.git is defined

    - name: process {{ _project_label }} bind mounts
      ansible.builtin.include_tasks: process-bind-mounts.yaml
      when: _process_bind_mounts

    - name: create {{ _project_label }} env files
      ansible.builtin.include_tasks: create-env-file.yaml
      loop: "{{ _services | selectattr('env_file', 'defined') }}"
      loop_control:
        label: "{{ service.name }}"
        loop_var: service

    - name: start {{ _project_label }} 
      community.docker.docker_compose_v2:
        state: present
        project_src: "{{ _project_dir }}"
        files:
          - "{{ _compose_file }}"
      when: _autostart
  when: _services | length > 0
