---
- name: create project directory
  file:
    dest: "{{ _docker_compose_project_dir }}"
    state: directory
    owner: "{{ _docker_compose_project_owner }}"
    group: "{{ _docker_compose_project_group }}"
    mode: "{{ _docker_compose_project_dir_mode }}"

- block:
    - name: generate docker-compose
      ansible.builtin.template:
        src: docker-compose.yaml.j2
        dest: "{{ _docker_compose_project_dir }}/docker-compose.yaml"
        owner: "{{ _docker_compose_project_owner }}"
        group: "{{ _docker_compose_project_group }}"
        mode: "{{ _docker_compose_project_mode }}"

    - name: pull docker images
      community.docker.docker_image:
        name: "{{ container.image.name if container.image is mapping else container.image }}"
        tag: "{{ container.image.tag | default('latest') if container.image is mapping else 'latest' }}"
        source: pull
      loop: "{{ _docker_compose_containers }}"
      loop_control:
        loop_var: container
        label: "{{ { 'service': container.service_name, 'image': container.image } }}"
      when: _docker_compose_pull_images

    - name: create volume bind mounts
      block:
        - name: get volume bind mounts for container
          ansible.builtin.set_fact:
            _docker_compose_bind_mounts: "{{ _docker_compose_bind_mounts + [ volume | combine({'source': volume.source if volume.source.startswith('/') else _docker_compose_project_dir ~ '/' ~ volume.source })] }}"
          loop: "{{ _docker_compose_containers | selectattr('volumes', 'defined') | map(attribute='volumes') | flatten | selectattr('source', 'defined') }}"
          loop_control:
            loop_var: volume
            label: "{{ volume.source if volume.source.startswith('/') else _docker_compose_project_dir ~ '/' ~ volume.source }}"
          vars:
            _docker_compose_bind_mounts: []

        - name: bind directory
          ansible.builtin.file:
            dest: "{{ volume.source if volume.source.startswith('/') else _docker_compose_project_dir ~ '/' ~ volume.source }}"
            state: directory
            owner: "{{ volume.owner | default(_docker_compose_project_bind_file_owner) }}"
            group: "{{ volume.group | default(_docker_compose_project_bind_file_group) }}"
            mode: "{{ volume.mode | default(_docker_compose_project_bind_file_mode) }}"
          loop: "{{ _docker_compose_bind_mounts | rejectattr('template', 'defined') | rejectattr('file', 'defined') }}"
          loop_control:
            loop_var: volume
            label: "{{ volume.source }}"
          when:
            - (volume.type | default('bind')) == 'bind'
            - volume.create | default(true)

        - name: bind file from template
          ansible.builtin.template:
            src: "{{ volume.template }}"
            dest: "{{ volume.source if volume.source.startswith('/') else _docker_compose_project_dir ~ '/' ~ volume.source }}"
            owner: "{{ volume.owner | default(_docker_compose_project_bind_file_owner) }}"
            group: "{{ volume.group | default(_docker_compose_project_bind_file_group) }}"
            mode: "{{ volume.mode | default(_docker_compose_project_bind_file_mode) }}"
          loop: "{{ _docker_compose_bind_mounts | selectattr('template', 'defined') | rejectattr('file', 'defined') }}"
          loop_control:
            loop_var: volume
            label: "{{ volume.source }}"
          when:
            - (volume.type | default('bind')) == 'bind'
            - volume.create | default(true)

        - name: bind file from source
          ansible.builtin.copy:
            src: "{{ volume.file }}"
            dest: "{{ volume.source if volume.source.startswith('/') else _docker_compose_project_dir ~ '/' ~ volume.source }}"
            owner: "{{ volume.owner | default(_docker_compose_project_bind_file_owner) }}"
            group: "{{ volume.group | default(_docker_compose_project_bind_file_group) }}"
            mode: "{{ volume.mode | default(_docker_compose_project_bind_file_mode) }}"
          loop: "{{ _docker_compose_bind_mounts | selectattr('file', 'defined') | rejectattr('template', 'defined') }}"
          loop_control:
            loop_var: volume
            label: "{{ volume.source }}"
          when:
            - (volume.type | default('bind')) == 'bind'
            - volume.create | default(true)
      when: _docker_compose_create_mounts

    - name: create env file
      ansible.builtin.include_tasks: create-env-file.yaml
      loop: "{{ _docker_compose_containers | selectattr('env_file', 'defined') }}"
      loop_control:
        label: "{{ container.service_name }}"
        loop_var: container

    - name: start docker compose
      community.docker.docker_compose_v2:
        state: present
        project_src: "{{ _docker_compose_project_dir }}"
      when: _docker_compose_autostart
  when: _docker_compose_containers | length > 0
