---
- name: reset variables
  ansible.builtin.set_fact:
    _build_context_root: []

- name: determine {{ _project_label }} build context root
  ansible.builtin.set_fact:
    _build_context_root: >-
      {{
        (service.build.context | default('.'))
          if (service.build.context | default('.')).startswith('/')
          else (_project_dir ~ '/' ~ (service.build.context | default('.'))) | replace('/.', '')
      }}

- name: create {{ _project_label }} build context root
  ansible.builtin.file:
    dest: "{{ _build_context_root }}"
    state: 'directory'
    owner: "{{ _project_owner }}"
    group: "{{ _project_group }}"
    mode: "{{ _project_dir_mode }}"
  when:
    - _build_context_root != _project_dir

- name: create {{ _project_label }} build context from source directory
  ansible.builtin.copy:
    src: "{{ service.build.src }}/"
    dest: "{{ _build_context_root }}"
    owner: "{{ _project_owner }}"
    group: "{{ _project_group }}"
    mode: "{{ _project_dir_mode }}"
    remote_src: "{{ context_file.remote | default(false) }}"
  when:
    - service.build.src is defined
    - service.build.git is not defined
    - service.build.files is not defined

- block:
    - name: determine {{ _project_label }} build context files
      ansible.builtin.set_fact:
        _context_files: >-
          {{
            _context_files + [
              context_file | combine({'path': _build_context_root ~ '/' ~ context_file.path })
            ]
          }}
      loop: "{{ service.build.files }}"
      loop_control:
        loop_var: context_file
        label: "{{ context_file.path }}"
      vars:
        _context_files: []

    - name: create {{ _project_label }} build context files from templates
      ansible.builtin.template:
        src: "{{ context_file.template }}"
        dest: "{{ context_file.path }}"
        owner: "{{ context_file.owner | default(_project_owner) }}"
        group: "{{ context_file.group | default(_project_group) }}"
        mode: "{{ context_file.mode | default(_compose_file_mode) }}"
      loop: >-
        {{
          _context_files
          | selectattr('template', 'defined')
          | rejectattr('file', 'defined')
          | rejectattr('data', 'defined')
          | rejectattr('lines', 'defined')
        }}
      loop_control:
        loop_var: context_file
        label: "{{ context_file.path }}"

    - name: create {{ _project_label }} build context files from data
      ansible.builtin.copy:
        dest: "{{ context_file.path }}"
        content: "{{ context_file.data if context_file.data is defined else context_file.lines | join('\n') }}"
        owner: "{{ context_file.owner | default(_project_owner) }}"
        group: "{{ context_file.group | default(_project_group) }}"
        mode: "{{ context_file.mode | default(_compose_file_mode) }}"
      loop: >-
        {{
          []
          | union(_data_context_files | selectattr('data', 'defined') | rejectattr('lines', 'defined'))
          | union(_data_context_files | selectattr('lines', 'defined') | rejectattr('data', 'defined'))
        }}
      loop_control:
        loop_var: context_file
        label: "{{ context_file.path }}"
      when:
        - context_file.create | default(true)
      vars:
        _data_context_files: "{{ _context_files | rejectattr('file', 'defined') | rejectattr('template', 'defined') }}"

    - name: copy {{ _project_label }} build context files from source files
      ansible.builtin.copy:
        src: "{{ context_file.file }}"
        dest: "{{ context_file.path }}"
        owner: "{{ context_file.owner | default(_project_owner) }}"
        group: "{{ context_file.group | default(_project_group) }}"
        mode: "{{ context_file.mode | default(_compose_file_mode) }}"
        remote_src: "{{ context_file.remote | default(false) }}"
      loop: >-
        {{
          _context_files
          | selectattr('file', 'defined')
          | rejectattr('template', 'defined')
          | rejectattr('data', 'defined')
          | rejectattr('lines', 'defined')
        }}
      loop_control:
        loop_var: context_file
        label: "{{ context_file.path }}"
  when:
    - service.build.files is defined
    - service.build.src is not defined
    - service.build.git is not defined

- name: create {{ _project_label }} build context from git repo
  ansible.builtin.git:
    repo: "{{ service.build.git.repo if service.build.git is mapping else service.build.git }}"
    dest: "{{ _build_context_root }}"
    version: "{{ service.build.git.version | default('HEAD') }}"
  when:
    - service.build.git is defined
    - service.build.src is not defined
    - service.build.files is not defined
