- name: generate docker compose files
  include_tasks: compose-project.yaml
  vars:
    _project_label: "{{ project.name | default(project.project_dir) ~ ' project' }}"
    _project_owner: "{{ project.project_owner | default(compose_owner) }}"
    _project_group: "{{ project.project_group | default(compose_group) }}"
    _project_dir: "{{ project.project_dir }}"
    _project_dir_mode: "{{ project.project_dir_mode | default(compose_dir_mode) }}"
    _compose_file: "{{ project.compose_file | default(compose_file) }}"
    _compose_file_mode: "{{ project.project_mode | default(compose_file_mode) }}"
    _bind_file_owner: "{{ project.default_file_owner | default(compose_bind_file_owner) }}"
    _bind_file_group: "{{ project.default_file_group | default(compose_bind_file_group) }}"
    _bind_file_mode: "{{ project.default_file_mode | default(compose_bind_file_mode) }}"
    _env_file_owner: "{{ project.env_file_owner | default(compose_env_file_owner) }}"
    _env_file_group: "{{ project.env_file_group | default(compose_env_file_group) }}"
    _env_file_mode: "{{ project.env_file_mode | default(compose_env_file_mode) }}"
    _services: "{{ project.services }}"
    _networks: "{{ project.networks | default(compose_default_networks) }}"
    _volumes: "{{ project.volumes | default(compose_default_volumes) }}"
    _autostart: "{{ project.autostart | default(compose_autostart) }}"
    _pull_images: "{{ project.pull_images | default(compose_pull_images) }}"
    _process_bind_mounts: "{{ project.process_bind_mounts | default(compose_process_bind_mounts) }}"
    _create_bind_mounts: "{{ project.create_mounts | default(compose_create_bind_mounts) }}"
  loop: "{{ compose_projects }}"
  loop_control:
    loop_var: project
    label: "{{ project.project_dir }}"
