---
- name: create project directory
  file:
    dest: "{{ docker_compose_project_dir }}"
    state: directory

- block:
    - name: generate docker-compose
      ansible.builtin.template:
        src: docker-compose.yaml.j2
        dest: "{{ docker_compose_project_dir }}/docker-compose.yaml"

    - name: pull docker images
      community.docker.docker_image:
        name: "{{ item.image }}"
        source: pull
      with_items: "{{ docker_compose_containers }}"
      when: docker_compose_pull_images

    - name: create volume mounts
      ansible.builtin.file:
        dest: "{{ item.source }}"
        state: "{{ item.state | default('directory') }}"
        owner: "{{ item.owner | default(omit) }}"
        group: "{{ item.group | default(omit) }}"
        mode: "{{ item.mode | default(omit) }}"
      with_items:
        - "{{ docker_compose_containers
              | selectattr('volumes', 'defined')
              | map(attribute='volumes')
              | flatten
              | selectattr('source', 'defined') }}"
      when: docker_compose_create_mounts

    - name: start docker compose
      community.docker.docker_compose:
        state: present
        project_src: "{{ docker_compose_project_dir }}"
      when: docker_compose_autostart
  when: docker_compose_containers | length > 0
