---
- name: create project directory
  file:
    dest: "{{ docker_compose_project_dir }}"
    state: directory

- block:
    - name: generate docker-compose
      ansible.builtin.template:
        src: docker-compose.yaml.j2
        dest: "{{ docker_compose_project_dir }}/docker-compose.yaml"
      notify: docker compose start

    - name: pull docker images
      community.docker.docker_image:
        name: "{{ item.image }}"
        source: pull
      with_items: "{{ docker_compose_containers }}"
      notify: docker compose start
      when: docker_compose_pull_images

    - name: create volume mounts
      ansible.builtin.file:
        dest: "{{ item.source }}"
        state: "{{ item.state | default('directory') }}"
      with_items:
        - "{{ docker_compose_containers
              | selectattr('volumes', 'defined')
              | map(attribute='volumes')
              | flatten
              | selectattr('source', 'defined') }}"
      when: docker_compose_create_mounts
  when: docker_compose_containers | length > 0
