- name: generate multiple docker compose files
  include_tasks: compose.yaml
  vars:
    _docker_compose_project_dir: "{{ project.project_dir }}"
    _docker_compose_project_owner: "{{ project.project_owner | default(docker_compose_project_owner) }}"
    _docker_compose_project_group: "{{ project.project_group | default(docker_compose_project_group) }}"
    _docker_compose_project_mode: "{{ project.project_mode | default(docker_compose_project_mode) }}"
    _docker_compose_project_dir_mode: "{{ project.project_dir_mode | default(docker_compose_project_dir_mode) }}"
    _docker_compose_containers: "{{ project.containers }}"
    _docker_compose_networks: "{{ project.networks | default(docker_compose_networks) }}"
    _docker_compose_volumes: "{{ project.volumes | default(docker_compose_volumes) }}"
    _docker_compose_autostart: "{{ project.autostart | default(docker_compose_autostart) }}"
    _docker_compose_pull_images: "{{ project.pull_images | default(docker_compose_pull_images) }}"
    _docker_compose_create_mounts: "{{ project.create_mounts | default(docker_compose_create_mounts) }}"
  loop: "{{ docker_compose_projects }}"
  loop_control:
    loop_var: project
  when: docker_compose_projects | length > 0

- name: generate single docker compose file
  include_tasks: compose.yaml
  vars:
    _docker_compose_project_dir: "{{ docker_compose_project_dir }}"
    _docker_compose_project_owner: "{{ docker_compose_project_owner }}"
    _docker_compose_project_group: "{{ docker_compose_project_group }}"
    _docker_compose_project_mode: "{{ docker_compose_project_mode }}"
    _docker_compose_project_dir_mode: "{{ docker_compose_project_dir_mode }}"
    _docker_compose_containers: "{{ docker_compose_containers }}"
    _docker_compose_networks: "{{ docker_compose_networks }}"
    _docker_compose_volumes: "{{ docker_compose_volumes }}"
    _docker_compose_autostart: "{{ docker_compose_autostart }}"
    _docker_compose_pull_images: "{{ docker_compose_pull_images }}"
    _docker_compose_create_mounts: "{{ docker_compose_create_mounts }}"
  when: docker_compose_projects | length == 0
