---
- name: reset variables
  ansible.builtin.set_fact:
    _docker_compose_bind_mounts: []

- name: determine {{ _docker_compose_project_label }} volume bind mounts
  ansible.builtin.set_fact:
    _docker_compose_bind_mounts: "{{ _docker_compose_bind_mounts + [ volume | combine({'source': volume.source if volume.source.startswith('/') else _docker_compose_project_dir ~ '/' ~ volume.source })] }}"
  loop: "{{ _docker_compose_containers | selectattr('volumes', 'defined') | map(attribute='volumes') | flatten | selectattr('source', 'defined') }}"
  loop_control:
    loop_var: volume
    label: "{{ volume.source if volume.source.startswith('/') else _docker_compose_project_dir ~ '/' ~ volume.source }}"
  when:
    - (volume.type | default('bind')) in ['bind', 'directory', 'file']
    - volume.create | default(_docker_compose_create_bind_mounts)

- name: bind {{ _docker_compose_project_label }} directories
  ansible.builtin.file:
    dest: "{{ volume.source if volume.source.startswith('/') else _docker_compose_project_dir ~ '/' ~ volume.source }}"
    state: directory
    owner: "{{ volume.owner | default(_docker_compose_project_bind_file_owner) }}"
    group: "{{ volume.group | default(_docker_compose_project_bind_file_group) }}"
    mode: "{{ volume.mode | default(_docker_compose_project_bind_file_mode) }}"
  loop: "{{ _docker_compose_bind_mounts | rejectattr('template', 'defined') | rejectattr('file', 'defined') | rejectattr('data', 'defined') | rejectattr('lines', 'defined') }}"
  loop_control:
    loop_var: volume
    label: "{{ volume.source }}"
  when:
    - (volume.type | default('directory')) == 'directory'

- name: bind {{ _docker_compose_project_label }} files
  ansible.builtin.file:
    dest: "{{ volume.source if volume.source.startswith('/') else _docker_compose_project_dir ~ '/' ~ volume.source }}"
    state: "{{ 'touch' if ((volume.type | default('directory')) == 'file') else omit }}"
    owner: "{{ volume.owner | default(_docker_compose_project_bind_file_owner) }}"
    group: "{{ volume.group | default(_docker_compose_project_bind_file_group) }}"
    mode: "{{ volume.mode | default(_docker_compose_project_bind_file_mode) }}"
    modification_time: preserve
    access_time: preserve
  loop: "{{ _docker_compose_bind_mounts | rejectattr('template', 'defined') | rejectattr('file', 'defined') | rejectattr('data', 'defined') | rejectattr('lines', 'defined') }}"
  loop_control:
    loop_var: volume
    label: "{{ volume.source }}"
  when:
    - (volume.type | default('directory')) in ['file', 'bind']

- name: bind {{ _docker_compose_project_label }} files from templates
  ansible.builtin.template:
    src: "{{ volume.template }}"
    dest: "{{ volume.source if volume.source.startswith('/') else _docker_compose_project_dir ~ '/' ~ volume.source }}"
    owner: "{{ volume.owner | default(_docker_compose_project_bind_file_owner) }}"
    group: "{{ volume.group | default(_docker_compose_project_bind_file_group) }}"
    mode: "{{ volume.mode | default(_docker_compose_project_bind_file_mode) }}"
  loop: "{{ _docker_compose_bind_mounts | selectattr('template', 'defined') | rejectattr('file', 'defined') | rejectattr('data', 'defined') | rejectattr('lines', 'defined') }}"
  loop_control:
    loop_var: volume
    label: "{{ volume.source }}"
  when:
    - (volume.type | default('file')) == 'file'

- name: create {{ _docker_compose_project_label }} files from data
  ansible.builtin.copy:
    dest: "{{ volume.source }}"
    content: "{{ volume.data if volume.data is defined else volume.lines | join('\n') }}"
    owner: "{{ volume.owner | default(_docker_compose_project_bind_file_owner) }}"
    group: "{{ volume.group | default(_docker_compose_project_bind_file_group) }}"
    mode: "{{ volume.mode | default(_docker_compose_project_bind_file_mode) }}" 
  loop: "{{ []
          | union(_data_volumes | selectattr('data', 'defined') | rejectattr('lines', 'defined'))
          | union(_data_volumes | selectattr('lines', 'defined') | rejectattr('data', 'defined'))
        }}"
  loop_control:
    loop_var: volume
    label: "{{ volume.source }}"
  when:
    - (volume.type | default('file')) == 'file'
  vars:
    _data_volumes: "{{ _docker_compose_bind_mounts | rejectattr('file', 'defined') | rejectattr('template', 'defined') }}"

- name: bind {{ _docker_compose_project_label }} files from source files
  ansible.builtin.copy:
    src: "{{ volume.file }}"
    dest: "{{ volume.source if volume.source.startswith('/') else _docker_compose_project_dir ~ '/' ~ volume.source }}"
    owner: "{{ volume.owner | default(_docker_compose_project_bind_file_owner) }}"
    group: "{{ volume.group | default(_docker_compose_project_bind_file_group) }}"
    mode: "{{ volume.mode | default(_docker_compose_project_bind_file_mode) }}"
    remote_src: "{{ volume.remote | default(false) }}"
  loop: "{{ _docker_compose_bind_mounts | selectattr('file', 'defined') | rejectattr('template', 'defined') | rejectattr('data', 'defined') | rejectattr('lines', 'defined') }}"
  loop_control:
    loop_var: volume
    label: "{{ volume.source }}"
  when:
    - (volume.type | default('file')) == 'file'
